### This application properties YAML provides specific overrides for the `local` profile.
###
### The datasource configuration is **deliberately omitted** so that it gets autoconfigured
### by Spring Boot Docker Compose support from the PostgreSQL service in `compose.yaml`.
###
### For more details, see **Service Connections** in the Spring Boot reference documentation:
###     https://docs.spring.io/spring-boot/reference/features/dev-services.html
###
### This is also the reason that the datasource for non-`local` profiles is defined in the
### second YAML document in `application.yml`.
###
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  zipkin:
    base-url: http://localhost:9411
    enabled: true

  # Micrometer tracing will handle local sampling
  management:
    tracing:
      enabled: true
      sampling:
        probability: 1.0

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [traceId=%X{traceId} spanId=%X{spanId}] %-5level %logger{0}.%M:%L - %msg%n"