---
# https://github.com/ministryofjustice/laa-provider-data-platform/blob/main/tech-docs/config/tech-docs.yml

host: https://ministryofjustice.github.io/laa-provider-data-platform
show_govuk_logo: false
service_name: Provider Data APIs
service_link: /
header_links:
  PDA-r1: /pda-r1/index.html
  PDA-r2: /pda-r2/index.html
  GitHub: https://github.com/ministryofjustice/laa-provider-data-platform/tree/main/tech-docs
enable_search: true
collapsible_nav: true
max_toc_heading_level: 3
prevent_indexing: false
show_contribution_banner: true
github_repo: ministryofjustice/laa-provider-data-platform
github_branch: main
full_service_name: LAA Digital Provider Data APIs
show_expiry: true
show_review_banner: true
