-- Initial schema. DDL derived from Hibernate's schema generation output
-- (jakarta.persistence.schema-generation) against PostgreSQL 17.

CREATE TABLE BANK_ACCOUNT (
    GUID                     UUID         NOT NULL,
    VERSION                  BIGINT,
    CREATED_BY               VARCHAR(255),
    CREATED_TIMESTAMP        TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY          VARCHAR(255),
    LAST_UPDATED_TIMESTAMP   TIMESTAMP(6) WITH TIME ZONE,
    ACCOUNT_NAME             VARCHAR(255) NOT NULL,
    ACCOUNT_NUMBER           VARCHAR(255) NOT NULL,
    SORT_CODE                VARCHAR(255) NOT NULL,
    PRIMARY KEY (GUID),
    CONSTRAINT UK_BANK_ACCOUNT_SORTCODE_ACCOUNTNUMBER
        UNIQUE (SORT_CODE, ACCOUNT_NUMBER)
);

CREATE TABLE CONTRACT_MANAGER (
    GUID                     UUID         NOT NULL,
    VERSION                  BIGINT,
    CREATED_BY               VARCHAR(255),
    CREATED_TIMESTAMP        TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY          VARCHAR(255),
    LAST_UPDATED_TIMESTAMP   TIMESTAMP(6) WITH TIME ZONE,
    CONTRACT_MANAGER_ID      VARCHAR(255) NOT NULL UNIQUE,
    EMAIL_ADDRESS            VARCHAR(255),
    FIRST_NAME               VARCHAR(255) NOT NULL,
    LAST_NAME                VARCHAR(255) NOT NULL,
    PRIMARY KEY (GUID)
);

CREATE TABLE LIAISON_MANAGER (
    GUID                     UUID         NOT NULL,
    VERSION                  BIGINT,
    CREATED_BY               VARCHAR(255),
    CREATED_TIMESTAMP        TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY          VARCHAR(255),
    LAST_UPDATED_TIMESTAMP   TIMESTAMP(6) WITH TIME ZONE,
    EMAIL_ADDRESS            VARCHAR(255) NOT NULL,
    FIRST_NAME               VARCHAR(255) NOT NULL,
    LAST_NAME                VARCHAR(255) NOT NULL,
    TELEPHONE_NUMBER         VARCHAR(255),
    PRIMARY KEY (GUID)
);

CREATE TABLE OFFICE (
    GUID                     UUID         NOT NULL,
    VERSION                  BIGINT,
    CREATED_BY               VARCHAR(255),
    CREATED_TIMESTAMP        TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY          VARCHAR(255),
    LAST_UPDATED_TIMESTAMP   TIMESTAMP(6) WITH TIME ZONE,
    ADDRESS_LINE1            VARCHAR(255) NOT NULL,
    ADDRESS_LINE2            VARCHAR(255),
    ADDRESS_LINE3            VARCHAR(255),
    ADDRESS_LINE4            VARCHAR(255),
    ADDRESS_TOWN_OR_CITY     VARCHAR(255) NOT NULL,
    ADDRESS_COUNTY           VARCHAR(255),
    ADDRESS_POST_CODE        VARCHAR(255) NOT NULL,
    DX_DETAILS_CENTRE        VARCHAR(255),
    DX_DETAILS_NUMBER        VARCHAR(255),
    EMAIL_ADDRESS            VARCHAR(255),
    TELEPHONE_NUMBER         VARCHAR(255),
    PRIMARY KEY (GUID)
);

-- Single-table inheritance: LSP, Chambers, Advocate (advocate/barrister subtypes) all in one table.
-- FIRM_TYPE is the discriminator column; ADVOCATE_TYPE further discriminates Advocate subtypes.
CREATE TABLE PROVIDER (
    GUID                                        UUID         NOT NULL,
    VERSION                                     BIGINT,
    CREATED_BY                                  VARCHAR(255),
    CREATED_TIMESTAMP                           TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY                             VARCHAR(255),
    LAST_UPDATED_TIMESTAMP                      TIMESTAMP(6) WITH TIME ZONE,
    FIRM_NUMBER                                 VARCHAR(255) NOT NULL UNIQUE,
    FIRM_TYPE                                   VARCHAR(255) NOT NULL,
    NAME                                        VARCHAR(255) NOT NULL,
    -- LSP-specific columns
    COMPANIES_HOUSE_NUMBER                      VARCHAR(255),
    CONSTITUTIONAL_STATUS                       VARCHAR(255),
    INDEMNITY_RECEIVED_DATE                     DATE,
    NOT_FOR_PROFIT_ORGANISATION_FLAG            BOOLEAN,
    -- Practitioner (Advocate/Barrister) columns
    ADVOCATE_TYPE                               VARCHAR(255),
    ADVOCATE_LEVEL                              VARCHAR(255),
    SOLICITOR_REGULATION_AUTHORITY_ROLL_NUMBER  VARCHAR(255),
    BARRISTER_LEVEL                             VARCHAR(255),
    BAR_COUNCIL_ROLL_NUMBER                     VARCHAR(255),
    PRIMARY KEY (GUID)
);

-- Single-table inheritance: LSP, Chambers, Advocate office links all in one table.
-- FIRM_TYPE is the discriminator column.
CREATE TABLE PROVIDER_OFFICE_LINK (
    GUID                     UUID         NOT NULL,
    VERSION                  BIGINT,
    CREATED_BY               VARCHAR(255),
    CREATED_TIMESTAMP        TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY          VARCHAR(255),
    LAST_UPDATED_TIMESTAMP   TIMESTAMP(6) WITH TIME ZONE,
    FIRM_TYPE                VARCHAR(31)  NOT NULL
        CHECK ((FIRM_TYPE IN ('ProviderOfficeLinkEntity', 'Advocate', 'Chambers', 'Legal Services Provider'))),
    ACCOUNT_NUMBER           VARCHAR(255) NOT NULL UNIQUE,
    PROVIDER_GUID            UUID         NOT NULL,
    OFFICE_GUID              UUID         NOT NULL,
    HEAD_OFFICE_FLAG         BOOLEAN      NOT NULL,
    ACTIVE_DATE_TO           DATE,
    WEBSITE                  VARCHAR(255),
    -- LSP- and Advocate-specific columns (shared column names)
    DEBT_RECOVERY_FLAG       BOOLEAN,
    FALSE_BALANCE_FLAG       BOOLEAN,
    INTERVENED_CHANGE_DATE   DATE,
    INTERVENED_FLAG          BOOLEAN,
    PAYMENT_HELD_FLAG        BOOLEAN,
    PAYMENT_HELD_REASON      VARCHAR(255),
    PAYMENT_METHOD           VARCHAR(255),
    VAT_REGISTRATION_NUMBER  VARCHAR(255),
    PRIMARY KEY (GUID),
    CONSTRAINT UK_PROVIDER_OFFICE_LINK_PROVIDER_OFFICE_FIRMTYPE
        UNIQUE (PROVIDER_GUID, OFFICE_GUID, FIRM_TYPE),
    CONSTRAINT FK_PROVIDER_OFFICE_LINK_PROVIDER
        FOREIGN KEY (PROVIDER_GUID) REFERENCES PROVIDER,
    CONSTRAINT FK_PROVIDER_OFFICE_LINK_OFFICE
        FOREIGN KEY (OFFICE_GUID) REFERENCES OFFICE
);

CREATE TABLE PROVIDER_BANK_ACCOUNT_LINK (
    GUID                     UUID         NOT NULL,
    VERSION                  BIGINT,
    CREATED_BY               VARCHAR(255),
    CREATED_TIMESTAMP        TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY          VARCHAR(255),
    LAST_UPDATED_TIMESTAMP   TIMESTAMP(6) WITH TIME ZONE,
    PROVIDER_GUID            UUID         NOT NULL,
    BANK_ACCOUNT_GUID        UUID         NOT NULL,
    PRIMARY KEY (GUID),
    CONSTRAINT UK_PROVIDER_BA_LINK_PROVIDER_BANK_ACCOUNT
        UNIQUE (PROVIDER_GUID, BANK_ACCOUNT_GUID),
    CONSTRAINT FK_PROVIDER_BA_LINK_PROVIDER
        FOREIGN KEY (PROVIDER_GUID) REFERENCES PROVIDER,
    CONSTRAINT FK_PROVIDER_BA_LINK_BANK_ACCOUNT
        FOREIGN KEY (BANK_ACCOUNT_GUID) REFERENCES BANK_ACCOUNT
);

CREATE TABLE PROVIDER_PARENT_LINK (
    GUID                     UUID         NOT NULL,
    VERSION                  BIGINT,
    CREATED_BY               VARCHAR(255),
    CREATED_TIMESTAMP        TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY          VARCHAR(255),
    LAST_UPDATED_TIMESTAMP   TIMESTAMP(6) WITH TIME ZONE,
    PROVIDER_GUID            UUID         NOT NULL,
    PARENT_GUID              UUID         NOT NULL,
    PRIMARY KEY (GUID),
    CONSTRAINT UK_PROVIDER_PARENT_LINK_PROVIDER_PARENT
        UNIQUE (PROVIDER_GUID, PARENT_GUID),
    CONSTRAINT FK_PROVIDER_PARENT_LINK_PROVIDER
        FOREIGN KEY (PROVIDER_GUID) REFERENCES PROVIDER,
    CONSTRAINT FK_PROVIDER_PARENT_LINK_PARENT
        FOREIGN KEY (PARENT_GUID) REFERENCES PROVIDER
);

CREATE TABLE OFFICE_BANK_ACCOUNT_LINK (
    GUID                        UUID         NOT NULL,
    VERSION                     BIGINT,
    CREATED_BY                  VARCHAR(255),
    CREATED_TIMESTAMP           TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY             VARCHAR(255),
    LAST_UPDATED_TIMESTAMP      TIMESTAMP(6) WITH TIME ZONE,
    PROVIDER_OFFICE_LINK_GUID   UUID         NOT NULL,
    BANK_ACCOUNT_GUID           UUID         NOT NULL,
    PRIMARY_FLAG                BOOLEAN      NOT NULL,
    ACTIVE_DATE_FROM            DATE         NOT NULL,
    ACTIVE_DATE_TO              DATE,
    PRIMARY KEY (GUID),
    CONSTRAINT UK_OFFICE_BA_LINK_PROVIDER_OFFICE_BANK_ACCOUNT
        UNIQUE (PROVIDER_OFFICE_LINK_GUID, BANK_ACCOUNT_GUID),
    CONSTRAINT FK_OFFICE_BA_LINK_PROVIDER_OFFICE
        FOREIGN KEY (PROVIDER_OFFICE_LINK_GUID) REFERENCES PROVIDER_OFFICE_LINK,
    CONSTRAINT FK_OFFICE_BA_LINK_BANK_ACCOUNT
        FOREIGN KEY (BANK_ACCOUNT_GUID) REFERENCES BANK_ACCOUNT
);

CREATE TABLE OFFICE_CONTRACT_MANAGER_LINK (
    GUID                     UUID         NOT NULL,
    VERSION                  BIGINT,
    CREATED_BY               VARCHAR(255),
    CREATED_TIMESTAMP        TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY          VARCHAR(255),
    LAST_UPDATED_TIMESTAMP   TIMESTAMP(6) WITH TIME ZONE,
    OFFICE_GUID              UUID         NOT NULL,
    CONTRACT_MANAGER_GUID    UUID         NOT NULL,
    PRIMARY KEY (GUID),
    CONSTRAINT UK_OFFICE_CONTRACT_MGR_LINK_OFFICE_CONTRACT_MGR
        UNIQUE (OFFICE_GUID, CONTRACT_MANAGER_GUID),
    CONSTRAINT FK_OFFICE_CONTRACT_MGR_LINK_OFFICE
        FOREIGN KEY (OFFICE_GUID) REFERENCES PROVIDER_OFFICE_LINK,
    CONSTRAINT FK_OFFICE_CONTRACT_MGR_LINK_CONTRACT_MGR
        FOREIGN KEY (CONTRACT_MANAGER_GUID) REFERENCES CONTRACT_MANAGER
);

CREATE TABLE OFFICE_LIAISON_MANAGER_LINK (
    GUID                     UUID         NOT NULL,
    VERSION                  BIGINT,
    CREATED_BY               VARCHAR(255),
    CREATED_TIMESTAMP        TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY          VARCHAR(255),
    LAST_UPDATED_TIMESTAMP   TIMESTAMP(6) WITH TIME ZONE,
    OFFICE_GUID              UUID         NOT NULL,
    LIAISON_MANAGER_GUID     UUID         NOT NULL,
    ACTIVE_DATE_FROM         DATE         NOT NULL,
    ACTIVE_DATE_TO           DATE,
    LINKED_FLAG              BOOLEAN      NOT NULL,
    PRIMARY KEY (GUID),
    CONSTRAINT UK_OFFICE_LIAISON_MGR_LINK_OFFICE_LIAISON_MGR
        UNIQUE (OFFICE_GUID, LIAISON_MANAGER_GUID),
    CONSTRAINT FK_OFFICE_LIAISON_MGR_LINK_OFFICE
        FOREIGN KEY (OFFICE_GUID) REFERENCES PROVIDER_OFFICE_LINK,
    CONSTRAINT FK_OFFICE_LIAISON_MGR_LINK_LIAISON_MGR
        FOREIGN KEY (LIAISON_MANAGER_GUID) REFERENCES LIAISON_MANAGER
);
