-- Hibernate Envers support for provider firm auditing.
-- REVINFO stores global revision metadata.
CREATE TABLE REVINFO (
    REV             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REVTSTMP        BIGINT       NOT NULL,
    REVISION_USER   VARCHAR(255) NOT NULL
);

-- PROVIDER_AUD stores a full snapshot for each provider revision.
CREATE TABLE PROVIDER_AUD (
    GUID                                        UUID         NOT NULL,
    REV                                         INTEGER      NOT NULL,
    REVTYPE                                     SMALLINT,
    FIRM_NUMBER                                 VARCHAR(255),
    FIRM_TYPE                                   VARCHAR(255),
    NAME                                        VARCHAR(255),
    COMPANIES_HOUSE_NUMBER                      VARCHAR(255),
    CONSTITUTIONAL_STATUS                       VARCHAR(255),
    INDEMNITY_RECEIVED_DATE                     DATE,
    NOT_FOR_PROFIT_ORGANISATION_FLAG            BOOLEAN,
    ADVOCATE_TYPE                               VARCHAR(255),
    ADVOCATE_LEVEL                              VARCHAR(255),
    SOLICITOR_REGULATION_AUTHORITY_ROLL_NUMBER  VARCHAR(255),
    BARRISTER_LEVEL                             VARCHAR(255),
    BAR_COUNCIL_ROLL_NUMBER                     VARCHAR(255),
    VERSION                                     BIGINT,
    CREATED_BY                                  VARCHAR(255),
    CREATED_TIMESTAMP                           TIMESTAMP(6) WITH TIME ZONE,
    LAST_UPDATED_BY                             VARCHAR(255),
    LAST_UPDATED_TIMESTAMP                      TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (GUID, REV),
    CONSTRAINT fk_provider_aud_revinfo
        FOREIGN KEY (REV)
            REFERENCES REVINFO (REV)
);

CREATE INDEX idx_provider_aud_rev
    ON PROVIDER_AUD (REV);

