CREATE TABLE OUTBOX_EVENT (
    GUID UUID NOT NULL DEFAULT gen_random_uuid(),
    VERSION BIGINT,
    CREATED_BY VARCHAR(255),
    CREATED_TIMESTAMP TIMESTAMPTZ,
    LAST_UPDATED_BY VARCHAR(255),
    LAST_UPDATED_TIMESTAMP TIMESTAMPTZ,
    AGGREGATE_TYPE VARCHAR(100) NOT NULL,
    AGGREGATE_ID UUID NOT NULL,
    EVENT_TYPE VARCHAR(100) NOT NULL,
    FIRM_NUMBER VARCHAR(50) NOT NULL,
    EVENT_PAYLOAD TEXT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    ATTEMPT_COUNT INTEGER NOT NULL DEFAULT 0,
    OCCURRED_AT TIMESTAMPTZ NOT NULL,
    SENT_AT TIMESTAMPTZ,
    LAST_ERROR VARCHAR(1000),
    CONSTRAINT pk_outbox_event PRIMARY KEY (GUID)
);

CREATE INDEX idx_outbox_event_status_occurred_at ON OUTBOX_EVENT (STATUS, OCCURRED_AT);
CREATE INDEX idx_outbox_event_aggregate ON OUTBOX_EVENT (AGGREGATE_ID, OCCURRED_AT);

