package uk.gov.justice.laa.providerdata.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;
import uk.gov.justice.laa.providerdata.entity.ContractManagerEntity;
import uk.gov.justice.laa.providerdata.model.ContractManagerV2;
import uk.gov.justice.laa.providerdata.model.OfficeContractManagerV2;

/**
 * Unit test for {@link ContractManagerMapper}.
 *
 * <p>This test class verifies that the mapping from {@link ContractManagerEntity} to {@link
 * OfficeContractManagerV2} works correctly using MapStruct.
 *
 * <p>It ensures that all relevant fields are mapped as expected.
 */
public class ContractManagerMapperTest {

  /** Mapper instance generated by MapStruct for {@link ContractManagerMapper}. */
  private final ContractManagerMapper mapper = Mappers.getMapper(ContractManagerMapper.class);

  @Test
  void shouldMapEntityToOfficeContractManagerDto() {
    ContractManagerEntity entity = contractManagerEntity();

    OfficeContractManagerV2 dto = mapper.toOfficeContractManagerV2(entity);

    assertCommonFields(
        dto.getGuid(),
        dto.getVersion(),
        dto.getCreatedBy(),
        dto.getCreatedTimestamp(),
        dto.getLastUpdatedBy(),
        dto.getLastUpdatedTimestamp(),
        dto.getContractManagerId(),
        dto.getFirstName(),
        dto.getLastName());
  }

  @Test
  void shouldMapEntityToContractManagerDto() {
    ContractManagerEntity entity = contractManagerEntity();

    ContractManagerV2 dto = mapper.toContractManagerV2(entity);

    assertCommonFields(
        dto.getGuid(),
        dto.getVersion(),
        dto.getCreatedBy(),
        dto.getCreatedTimestamp(),
        dto.getLastUpdatedBy(),
        dto.getLastUpdatedTimestamp(),
        dto.getContractManagerId(),
        dto.getFirstName(),
        dto.getLastName());
  }

  private static ContractManagerEntity contractManagerEntity() {
    return ContractManagerEntity.builder()
        .guid(UUID.fromString("11111111-1111-1111-1111-111111111111"))
        .version(12L)
        .createdBy("john.smith.42")
        .createdTimestamp(OffsetDateTime.parse("2025-09-25T09:30:00Z"))
        .lastUpdatedBy("john.doe.24")
        .lastUpdatedTimestamp(OffsetDateTime.parse("2025-09-26T12:30:00Z"))
        .contractManagerId("123")
        .firstName("John")
        .lastName("Smith")
        .build();
  }

  private static void assertCommonFields(
      String guid,
      BigDecimal version,
      String createdBy,
      OffsetDateTime createdTimestamp,
      String lastUpdatedBy,
      OffsetDateTime lastUpdatedTimestamp,
      String contractManagerId,
      String firstName,
      String lastName) {
    assertThat(guid).isEqualTo("11111111-1111-1111-1111-111111111111");
    assertThat(version).hasToString("12");
    assertThat(createdBy).isEqualTo("john.smith.42");
    assertThat(createdTimestamp).isEqualTo(OffsetDateTime.parse("2025-09-25T09:30:00Z"));
    assertThat(lastUpdatedBy).isEqualTo("john.doe.24");
    assertThat(lastUpdatedTimestamp).isEqualTo(OffsetDateTime.parse("2025-09-26T12:30:00Z"));
    assertThat(contractManagerId).isEqualTo("123");
    assertThat(firstName).isEqualTo("John");
    assertThat(lastName).isEqualTo("Smith");
  }
}
