package uk.gov.justice.laa.providerdata.mapper;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;
import uk.gov.justice.laa.providerdata.entity.ContractManagerEntity;
import uk.gov.justice.laa.providerdata.model.OfficeContractManagerV2;

/**
 * Unit test for {@link ContractManagerMapper}.
 *
 * <p>This test class verifies that the mapping from {@link ContractManagerEntity} to {@link
 * OfficeContractManagerV2} works correctly using MapStruct.
 *
 * <p>It ensures that all relevant fields are mapped as expected.
 */
public class ContractManagerMapperTest {

  /** Mapper instance generated by MapStruct for {@link ContractManagerMapper}. */
  private final ContractManagerMapper mapper = Mappers.getMapper(ContractManagerMapper.class);

  /**
   * Tests that a {@link ContractManagerEntity} is correctly mapped to {@link
   * OfficeContractManagerV2}.
   *
   * <p>Verifies that the {@code contractManagerId}, {@code firstName}, and {@code lastName} fields
   * are correctly transferred from the entity to the DTO.
   */
  @Test
  void shouldMapEntityToDto() {

    ContractManagerEntity entity =
        ContractManagerEntity.builder()
            .contractManagerId("123")
            .firstName("John")
            .lastName("Smith")
            .build();

    OfficeContractManagerV2 dto = mapper.toOfficeContractManagerV2(entity);

    assertThat(dto.getContractManagerId()).isEqualTo("123");
    assertThat(dto.getFirstName()).isEqualTo("John");
    assertThat(dto.getLastName()).isEqualTo("Smith");
  }
}
