name: "Pipeline: PR opened/updated"

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    paths-ignore: [ "tech-docs/**" ]

concurrency:
  group: "pipeline-pdp-pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  plan:
    name: "Plan"
    permissions: { contents: read }
    runs-on: ubuntu-latest
    outputs:
      prnum:      ${{ steps.vars.outputs.prnum }}       # pull request number (e.g. `835`)
      short:      ${{ steps.vars.outputs.short }}       # short SHA to use in immutable registry tags (e.g. `0fe21ac`)
      no_preview: ${{ steps.vars.outputs.no_preview }}  # don't deploy a preview app (e.g. `true`)
    steps:
      - name: "Determine variable values"
        id:   vars
        shell: bash
        run: |
          set -eu
          PRNUM="${{ github.event.pull_request.number }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"   # PR head, not merge SHA
          SHORT="${HEAD_SHA::7}"
          NO_PREVIEW=$(jq -r 'any((. // [])[]; .name=="no-preview")' <<< '${{ toJson(github.event.pull_request.labels) }}')
          echo "- github.event_name=${{ github.event_name }}"
          echo "- github.event.pull_request.number=${{ github.event.pull_request.number }}"
          echo "- github.event.pull_request.head.sha=${{ github.event.pull_request.head.sha }}"
          echo "- outputs.prnum=$PRNUM"
          echo "- outputs.short=$SHORT"
          echo "- outputs.no_preview=$NO_PREVIEW"
          {
            echo "prnum=$PRNUM"
            echo "short=$SHORT"
            echo "no_preview=$NO_PREVIEW"
          } >> "$GITHUB_OUTPUT"

  source-scan:
    name: "Source scan"
    needs: [ plan ]
    permissions: { contents: read }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - run: |
          ### Check the Helm chart lints OK
          helm lint ./helm_deploy/provider-data-platform --quiet --strict

  gradle-build-and-publish:
    name: "Build PR #${{ needs.plan.outputs.prnum }}"
    needs: [ plan ]
    permissions: { contents: read, packages: write }
    uses: ./.github/workflows/rw-gradle-build-and-publish.yml
    with:
      itag: "pr-${{ needs.plan.outputs.prnum }}-${{ needs.plan.outputs.short }}"
    secrets:
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  ecr-publish-image:
    name: "Publish PR #${{ needs.plan.outputs.prnum }}"
    needs: [ plan, gradle-build-and-publish ]
    permissions: { actions: read, contents: read, id-token: write, packages: read, security-events: write }
    uses: ./.github/workflows/rw-ecr-publish-image.yml
    with:
      itag: "pr-${{ needs.plan.outputs.prnum }}-${{ needs.plan.outputs.short }}"
      mtag: "pr-${{ needs.plan.outputs.prnum }}"
    secrets:
      ecr_region:         ${{ vars.DPD_ECR_REGION }}
      ecr_repository:     ${{ vars.DPD_ECR_REPOSITORY }}
      ecr_role_to_assume: ${{ secrets.DPD_ECR_ROLE_TO_ASSUME }}
      snyk_token:         ${{ secrets.SNYK_TOKEN }}
      slack_webhook:      ${{ secrets.SLACK_WEBHOOK }}

  deploy-pr:
    name: "Deploy PR #${{ needs.plan.outputs.prnum }}"
    if:   needs.plan.outputs.no_preview != 'true'
    needs: [ plan, ecr-publish-image ]
    permissions: { contents: read, id-token: write }
    uses: ./.github/workflows/rw-pdp-deploy-pr.yml
    with:
      prnum:  ${{ needs.plan.outputs.prnum }}
      target: "uat"
      rtag:   "pr-${{ needs.plan.outputs.prnum }}-${{ needs.plan.outputs.short }}"
    secrets:
      ecr_region:         ${{ vars.DPD_ECR_REGION }}
      ecr_repository:     ${{ vars.DPD_ECR_REPOSITORY }}
      ecr_role_to_assume: ${{ secrets.DPD_ECR_ROLE_TO_ASSUME }}
      ip_allowlist:       ${{ secrets.IP_ALLOWLIST }}
      kube_cert:          ${{ secrets.KUBE_CERT }}
      kube_cluster:       ${{ secrets.KUBE_CLUSTER }}
      kube_namespace:     ${{ secrets.KUBE_NAMESPACE }}
      kube_token:         ${{ secrets.DEPLOYER_KUBE_TOKEN }}

  e2etest-pr:
    name: "E2E test PR #${{ needs.plan.outputs.prnum }}"
    needs: [ plan, deploy-pr ]
    permissions: { contents: read, packages: read }
    uses: ./.github/workflows/rw-pdp-e2etest.yml
    with:
      target:     "uat"
      rel:        "pr-${{ needs.plan.outputs.prnum }}"
      e2eProfile: "preview"
    secrets:
      kube_cert:      ${{ secrets.KUBE_CERT }}
      kube_cluster:   ${{ secrets.KUBE_CLUSTER }}
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_token:     ${{ secrets.E2ETESTER_KUBE_TOKEN }}
